export enum ICON_FAMILIES {
    ANT_DESIGN = "AntDesign",
    ENTYPO = "Entypo",
    EVIL_ICONS = "EvilIcons",
    FEATHER = "Feather",
    FONT_AWESOME = "FontAwesome",
    FONT_AWESOME_5 = "FontAwesome5",
    FONT_AWESOME_5_PRO = "FontAwesome5Pro",
    FONTISTO = "Fontisto",
    FOUNDATION = "Foundation",
    IONICONS = "Ionicons",
    MATERIAL_ICONS = "MaterialIcons",
    MATERIAL_COMMUNITY_ICONS = "MaterialCommunityIcons",
    OCTICONS = "Octicons",
    ZOCIAL = "Zocial",
    SIMPLE_LINE_ICONS = "SimpleLineIcons",
}
